# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 990f5f5b19fd70ea5982dccb08a93c177ce182622d959df0936c2d94660bae59a90dd4535c160d61f110e267e5d91caf42a5934dfbd2d8f98d7addabd7c2cd17

test:
  secret_key_base: 124da14cb2acda3b03547951d67bf8b26aac0522789c69d26eb4c9179b981e8faad3ed6c94426833a2b20642def6ee2c4b28eaa63704b123964be757b88750d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
